query Countries {
  countries {
    id
    code
    name
    emoji
  }
}


query CountryWithContinent($code: String!) {
  country(code: $code) {
    id
    code
    name
    emoji
    continent {
      name
      id
    }
  }
}

mutation AddCountry($data: NewCountryInput!) {
  addCountry(data: $data) {
    id
    code
    name
    emoji
  }
}